### ISSUE TITLE
Multiline string causes FC002 false positive (string interpolation)

### ISSUE THREAD

**Issue by monkey1016** [acrmp/foodcritic#308]
Hi,
I'm running foodcritic on our cookbooks and I think I came across a false positive for `FC002`:
```ruby
default['service']['rabbitmq']['uri'] = "amqp://#{default['service']['rabbitmq']['user']}:"\
        "#{default['service']['rabbitmq']['password']}@#{default['service']['rabbitmq']['host']}:"\
        "#{default['service']['rabbitmq']['port']}/"\
        "#{default['service']['rabbitmq']['vhost']}"
```

The above is found in one of our attribute files, triggering a `FC002` warning.

But just in case I'm wrong about the false positive, any suggestions on the correct way? :)
Thanks

**Comment by odcinek** [comment]
The rule is right - interpolation is not needed on lines 3 and 4. You might want to do

```ruby
default['service']['rabbitmq']['uri'] = "amqp://#{default['service']['rabbitmq']['user']}:" +
        "#{default['service']['rabbitmq']['password']}@#{default['service']['rabbitmq']['host']}:" +
        default['service']['rabbitmq']['port'] +
        default['service']['rabbitmq']['vhost']
```

**Comment by monkey1016** [comment]
Ok thanks.  You suggestion cleared it up.

**Comment by youhyunkim** [comment]
Hey @odcinek just curious if you have any solution without using the '+' symbol.
I only ask because there's a rubocop constraint. The warning reads:

> Use \ instead of + or << to concatenate those strings.

I typically like to run both rubocop and foodcritic to clean up my recipes and seems like this is always an issue for me when trying to interpolate long strings over multiple lines.

Thanks
