### ISSUE TITLE
Github pages have drifted from foodcritic.io

### ISSUE THREAD

**Issue by philoserf** [acrmp/foodcritic#332]
It appears the gh-pages branch hasn't been maintained in favor of the more attractive foodcritic.io. This may be an issue since https://acrmp.github.io/foodcritic/ still appears frequently in google search results.

Examples of content at https://acrmp.github.io/foodcritic/ but not at http://www.foodcritic.io/ include:

* rake task description
* FAQ

**Comment by philoserf** [comment]
Perhaps a conversation might be had here about what to migrate from gh-pages to https://github.com/acrmp/foodcritic-site.

Once that was completed we could update the local gh-pages to redirect to foodcritic.io (or alternatively migrate the foodcritic-site back here to gh-pages).

**Comment by acrmp** [comment]
Hi Mark,

Thanks for raising this. The original reason for not removing the `gh-pages` site was because it had content not available on the newer site. However I think this was a bad call given the confusion it caused.

The `gh-pages` site now redirects to [www.foodcritic.io](http://www.foodcritic.io). The earlier content is still available in git if we need to bring some of it across.

The newer site is hosted on S3. Travis does not do the publishing, so in addition to repo rights maintainers also need AWS credentials to publish to it.

Cheers,

Andrew.

**Comment by philoserf** [comment]
:+1:
