### ISSUE TITLE
New rule to check whether top-level attribute key matches cookbook name

### ISSUE THREAD

**Issue by patcon** [acrmp/foodcritic#383]
This seems to heavy-handed, as it doesn't deal with overriding another cookbook, but I thought I'd put it out there for discussion anyhow. Might make sense as a non-failing test, if those exist.

I haven't dug into the foodcritic issue queue, and also thought perhaps there were discussions of rulesets specific to cookbook types (_environment_, _application_, _library_ and _wrapper_, at least according to `berks help cookbook` output)

**Comment by patcon** [comment]
cc: @sethvargo as he made reference to this convention in "Learning Chef", and haven't really seen it elsewhere

**Comment by Rockstar04** [comment]
I think this would be a good idea a well, really helpful for new users starting out writing cookbooks!

**Comment by chris-rock** [comment]
I agree, this is useful, especially if you use multiple open source cookbooks

**Comment by lamont-granquist** [comment]
So the biggest issue I see with this is that in wrapper/role/application cookbooks, you typically do want to override other cookbook's attributes.  My base role cookbooks typically have very large attributes files that are nothing more than setting attributes for openssh, ntp, chef-client and other cookbooks.

We might be able to include a rule that you should only set attributes in your own cookbook namespace or in the namespace of cookbooks that you depend on.   But since foodcritic is a static analysis tool we'd always trigger incorrectly when we depend on a transitive cookbook but set a value on one of its deps (which would be perfectly fine in the case of a role cookbook depending on a wrapper cookbook which wrapped a supermarket library cookbook).

**Comment by tas50** [comment]
I think Lamont points out why this doesn't work. We've heavily encouraged writing wrapper cookbooks and in wrapper cookbooks you often set attributes that aren't those of your cookbook. It would make this false positive on every internal wrapper cookbook. That makes it pretty much near impossible to implement.
