### ISSUE TITLE
Remove contentious rule FC001

### ISSUE THREAD

**Issue by jtimberman** [acrmp/foodcritic#86]
Originally the FC001 rule matched against symbols, which I brought up (issue #1) as contrary to what Opscode and other Chef trainers using Opscode's materials teach students, which is to access node attributes with strings as keys.

Read the original issue for more background on my reasoning. The rule itself is contentious, as people have varying preference between node attributes as a string, symbol or method. Symbols are the leading way to access attributes per the survey I posted (233 respondents in ~2 weeks), followed by strings. While this is not representative of every Chef user, the trend for these %'s was consistent while the survey was open.

This rule was brought up in assorted conversations at the Chef Community Summit last week, and I propose that the rule be removed from foodcritic entirely. Functionally there is absolutely no difference between symbols and strings, as symbols in node attributes are converted to strings by the underlying library anyway. This is purely a "what color should we paint the bikeshed?" issue.

Here's the pie graph of the survey's results:

https://www.evernote.com/shard/s5/sh/1fc5a0c9-bdd0-44f4-8f5a-ed2ddc9d2cfd/a13f36acd7cfa2a468f7829e5549209f

**Comment by lamont-granquist** [comment]
Dunno if anyone still cares, but the Chef implementation of Mashes converts all symbols internally to strings anyway, so arguments about how ruby does things are irrelevant since symbols are always slower in Chef.  Given that and the fact that new users will stumble over `:foo_bar` working vs. `:foo-bar` failing (and then needing to learn the `:"foo-bar"` syntax), the winner here is strings.

And it used to be doubly-awful to use symbols since not only would they get converted to strings, but the symbols that were created first would never be garbage collected until very recent MRI rubies.
